---

- hosts: localhost
  tasks:
    - name: Load playbook vars
      include_vars:
        file: "vars/main.yml"

    - name: Load vault vars
      include_vars: "{{ lookup('first_found', possible_files) }}"
      vars:
        possible_files:
          - "{{ vault }}"
          - "vars/vault.yml"

    - name: Gather information about server
      os_server_info:
        auth:
          auth_url: "{{ url }}"
          username: "{{ os_user }}"
          password: "{{ os_passwd }}"
          project_name: "{{ project }}"
          os_project_domain_name: "{{ project_domain }}"
          os_user_domain_name: "{{ user_domain }}"
        server: "{{ vm_name }}"
        filters:
          vm_state: active
      register: vminfo
      delegate_to: localhost

    - debug:
        msg: "{{ vminfo.openstack_servers }}"

    - template:
        src: vminfo.json.j2
        dest: ./output/vminfo.json
      delegate_to: localhost
